# Generated by Django 5.2 on 2025-05-13 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '__first__'),
        ('servicos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Aguardando', 'Aguardando'), ('Em Lavagem', 'Em Lavagem'), ('Finalizado', 'Finalizado')], default='Aguardando', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_cliente', to='clientes.cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_servico', to='servicos.servico')),
            ],
        ),
    ]
